/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_Mapnik */

#ifndef _Included_es_predictia_pdts_mapnikjni_Mapnik
#define _Included_es_predictia_pdts_mapnikjni_Mapnik
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_predictia_pdts_mapnikjni_Mapnik
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Mapnik_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     es_predictia_pdts_mapnikjni_Mapnik
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_Mapnik_version
  (JNIEnv *, jclass);

/*
 * Class:     es_predictia_pdts_mapnikjni_Mapnik
 * Method:    getInstalledFontsDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_Mapnik_getInstalledFontsDir
  (JNIEnv *, jclass);

/*
 * Class:     es_predictia_pdts_mapnikjni_Mapnik
 * Method:    getInstalledInputPluginsDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_Mapnik_getInstalledInputPluginsDir
  (JNIEnv *, jclass);

/*
 * Class:     es_predictia_pdts_mapnikjni_Mapnik
 * Method:    isThreadSafe
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_es_predictia_pdts_mapnikjni_Mapnik_isThreadSafe
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
