/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_Geometry */

#ifndef _Included_es_predictia_pdts_mapnikjni_Geometry
#define _Included_es_predictia_pdts_mapnikjni_Geometry
#ifdef __cplusplus
extern "C" {
#endif
#undef es_predictia_pdts_mapnikjni_Geometry_TYPE_POINT
#define es_predictia_pdts_mapnikjni_Geometry_TYPE_POINT 1L
#undef es_predictia_pdts_mapnikjni_Geometry_TYPE_LINESTRING
#define es_predictia_pdts_mapnikjni_Geometry_TYPE_LINESTRING 2L
#undef es_predictia_pdts_mapnikjni_Geometry_TYPE_POLYGON
#define es_predictia_pdts_mapnikjni_Geometry_TYPE_POLYGON 3L
#undef es_predictia_pdts_mapnikjni_Geometry_TYPE_MULTIPOINT
#define es_predictia_pdts_mapnikjni_Geometry_TYPE_MULTIPOINT 4L
#undef es_predictia_pdts_mapnikjni_Geometry_TYPE_MULTILINESTRING
#define es_predictia_pdts_mapnikjni_Geometry_TYPE_MULTILINESTRING 5L
#undef es_predictia_pdts_mapnikjni_Geometry_TYPE_MULTIPOLYGON
#define es_predictia_pdts_mapnikjni_Geometry_TYPE_MULTIPOLYGON 6L
/*
 * Class:     es_predictia_pdts_mapnikjni_Geometry
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_Geometry_getType
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_Geometry
 * Method:    getNumPoints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_Geometry_getNumPoints
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_Geometry
 * Method:    getVertex
 * Signature: (ILes/predictia/pdts/mapnikjni/Coord;)I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_Geometry_getVertex
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_Geometry
 * Method:    getEnvelope
 * Signature: ()Les/predictia/pdts/mapnikjni/Box2d;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_Geometry_getEnvelope
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
