/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_Projection */

#ifndef _Included_es_predictia_pdts_mapnikjni_Projection
#define _Included_es_predictia_pdts_mapnikjni_Projection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_predictia_pdts_mapnikjni_Projection
 * Method:    alloc
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_es_predictia_pdts_mapnikjni_Projection_alloc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_Projection
 * Method:    isProjSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_es_predictia_pdts_mapnikjni_Projection_isProjSupported
  (JNIEnv *, jclass);

/*
 * Class:     es_predictia_pdts_mapnikjni_Projection
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Projection_dealloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_predictia_pdts_mapnikjni_Projection
 * Method:    getParams
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_Projection_getParams
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_Projection
 * Method:    getExpanded
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_Projection_getExpanded
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_Projection
 * Method:    forward
 * Signature: (Les/predictia/pdts/mapnikjni/Coord;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Projection_forward
  (JNIEnv *, jobject, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_Projection
 * Method:    inverse
 * Signature: (Les/predictia/pdts/mapnikjni/Coord;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Projection_inverse
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
