/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_FreetypeEngine */

#ifndef _Included_es_predictia_pdts_mapnikjni_FreetypeEngine
#define _Included_es_predictia_pdts_mapnikjni_FreetypeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_predictia_pdts_mapnikjni_FreetypeEngine
 * Method:    registerFont
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_es_predictia_pdts_mapnikjni_FreetypeEngine_registerFont
  (JNIEnv *, jclass, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_FreetypeEngine
 * Method:    registerFonts
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_es_predictia_pdts_mapnikjni_FreetypeEngine_registerFonts
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     es_predictia_pdts_mapnikjni_FreetypeEngine
 * Method:    isFontFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_es_predictia_pdts_mapnikjni_FreetypeEngine_isFontFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
