/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_Renderer */

#ifndef _Included_es_predictia_pdts_mapnikjni_Renderer
#define _Included_es_predictia_pdts_mapnikjni_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_predictia_pdts_mapnikjni_Renderer
 * Method:    renderAgg
 * Signature: (Les/predictia/pdts/mapnikjni/MapDefinition;Les/predictia/pdts/mapnikjni/Image;DII)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Renderer_renderAgg
  (JNIEnv *, jclass, jobject, jobject, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
