/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_Query */

#ifndef _Included_es_predictia_pdts_mapnikjni_Query
#define _Included_es_predictia_pdts_mapnikjni_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_predictia_pdts_mapnikjni_Query
 * Method:    alloc
 * Signature: (Les/predictia/pdts/mapnikjni/Box2d;DDD)J
 */
JNIEXPORT jlong JNICALL Java_es_predictia_pdts_mapnikjni_Query_alloc
  (JNIEnv *, jclass, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     es_predictia_pdts_mapnikjni_Query
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Query_dealloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_predictia_pdts_mapnikjni_Query
 * Method:    addPropertyName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Query_addPropertyName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
