/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_MapDefinition */

#ifndef _Included_es_predictia_pdts_mapnikjni_MapDefinition
#define _Included_es_predictia_pdts_mapnikjni_MapDefinition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    alloc
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_alloc__IILjava_lang_String_2
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_alloc__
  (JNIEnv *, jclass);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_dealloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    loadMap
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_loadMap
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    loadMapString
 * Signature: (Ljava/lang/String;ZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_loadMapString
  (JNIEnv *, jobject, jstring, jboolean, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setHeight
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getSrs
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getSrs
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setSrs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setSrs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setBufferSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getBasePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getBasePath
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setBasePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setBasePath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getLayerCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getLayerCount
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getLayer
 * Signature: (I)Les/predictia/pdts/mapnikjni/Layer;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getLayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setLayer
 * Signature: (ILes/predictia/pdts/mapnikjni/Layer;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setLayer
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    removeLayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_removeLayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    removeAllLayers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_removeAllLayers
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    addLayer
 * Signature: (Les/predictia/pdts/mapnikjni/Layer;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_addLayer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    _setAspectFixMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition__1setAspectFixMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    _getAspectFixMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition__1getAspectFixMode
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getStyleNames
 * Signature: ()Ljava/util/Collection;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getStyleNames
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getStyle
 * Signature: (Ljava/lang/String;)Les/predictia/pdts/mapnikjni/FeatureTypeStyle;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getStyle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    addStyle
 * Signature: (Ljava/lang/String;Les/predictia/pdts/mapnikjni/FeatureTypeStyle;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_addStyle
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    removeStyle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_removeStyle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getMaximumExtent
 * Signature: ()Les/predictia/pdts/mapnikjni/Box2d;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getMaximumExtent
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setMaximumExtent
 * Signature: (Les/predictia/pdts/mapnikjni/Box2d;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setMaximumExtent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getCurrentExtent
 * Signature: ()Les/predictia/pdts/mapnikjni/Box2d;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getCurrentExtent
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getBufferedExtent
 * Signature: ()Les/predictia/pdts/mapnikjni/Box2d;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getBufferedExtent
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    zoom
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_zoom
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    zoomToBox
 * Signature: (Les/predictia/pdts/mapnikjni/Box2d;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_zoomToBox
  (JNIEnv *, jobject, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    zoomAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_zoomAll
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    pan
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_pan
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    panAndZoom
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_panAndZoom
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getScale
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getScale
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getScaleDenominator
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getScaleDenominator
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getBackground
 * Signature: ()Les/predictia/pdts/mapnikjni/Color;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getBackground
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setBackground
 * Signature: (Les/predictia/pdts/mapnikjni/Color;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setBackground
  (JNIEnv *, jobject, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    getBackgroundImage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_getBackgroundImage
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    setBackgroundImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_setBackgroundImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    saveMap
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_saveMap
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     es_predictia_pdts_mapnikjni_MapDefinition
 * Method:    saveMapToString
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_es_predictia_pdts_mapnikjni_MapDefinition_saveMapToString
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
