/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_Parameters */

#ifndef _Included_es_predictia_pdts_mapnikjni_Parameters
#define _Included_es_predictia_pdts_mapnikjni_Parameters
#ifdef __cplusplus
extern "C" {
#endif
#undef es_predictia_pdts_mapnikjni_Parameters_serialVersionUID
#define es_predictia_pdts_mapnikjni_Parameters_serialVersionUID 362498820763181265LL
#undef es_predictia_pdts_mapnikjni_Parameters_DEFAULT_INITIAL_CAPACITY
#define es_predictia_pdts_mapnikjni_Parameters_DEFAULT_INITIAL_CAPACITY 16L
#undef es_predictia_pdts_mapnikjni_Parameters_MAXIMUM_CAPACITY
#define es_predictia_pdts_mapnikjni_Parameters_MAXIMUM_CAPACITY 1073741824L
#undef es_predictia_pdts_mapnikjni_Parameters_DEFAULT_LOAD_FACTOR
#define es_predictia_pdts_mapnikjni_Parameters_DEFAULT_LOAD_FACTOR 0.75f
#undef es_predictia_pdts_mapnikjni_Parameters_TREEIFY_THRESHOLD
#define es_predictia_pdts_mapnikjni_Parameters_TREEIFY_THRESHOLD 8L
#undef es_predictia_pdts_mapnikjni_Parameters_UNTREEIFY_THRESHOLD
#define es_predictia_pdts_mapnikjni_Parameters_UNTREEIFY_THRESHOLD 6L
#undef es_predictia_pdts_mapnikjni_Parameters_MIN_TREEIFY_CAPACITY
#define es_predictia_pdts_mapnikjni_Parameters_MIN_TREEIFY_CAPACITY 64L
/*
 * Class:     es_predictia_pdts_mapnikjni_Parameters
 * Method:    setNativeInt
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Parameters_setNativeInt
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     es_predictia_pdts_mapnikjni_Parameters
 * Method:    setNativeString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Parameters_setNativeString
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     es_predictia_pdts_mapnikjni_Parameters
 * Method:    setNativeDouble
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_Parameters_setNativeDouble
  (JNIEnv *, jclass, jlong, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
