/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_predictia_pdts_mapnikjni_FeatureSet */

#ifndef _Included_es_predictia_pdts_mapnikjni_FeatureSet
#define _Included_es_predictia_pdts_mapnikjni_FeatureSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_predictia_pdts_mapnikjni_FeatureSet
 * Method:    dealloc
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_es_predictia_pdts_mapnikjni_FeatureSet_dealloc
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     es_predictia_pdts_mapnikjni_FeatureSet
 * Method:    _next
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_es_predictia_pdts_mapnikjni_FeatureSet__1next
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_FeatureSet
 * Method:    _loadGeometries
 * Signature: ()[Les/predictia/pdts/mapnikjni/Geometry;
 */
JNIEXPORT jobjectArray JNICALL Java_es_predictia_pdts_mapnikjni_FeatureSet__1loadGeometries
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_FeatureSet
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_predictia_pdts_mapnikjni_FeatureSet_getId
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_FeatureSet
 * Method:    getEnvelope
 * Signature: ()Les/predictia/pdts/mapnikjni/Box2d;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_FeatureSet_getEnvelope
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_FeatureSet
 * Method:    getPropertyNames
 * Signature: ()Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_FeatureSet_getPropertyNames
  (JNIEnv *, jobject);

/*
 * Class:     es_predictia_pdts_mapnikjni_FeatureSet
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_es_predictia_pdts_mapnikjni_FeatureSet_getProperty
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
